### ISSUE TITLE
better PCRE2 compilation errors

### ISSUE THREAD

**Issue by rexim** [tsoding/vodus#136]
introduced in #134

**Comment by rexim** [comment]
Invalidated by #149
